BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bbappend"
BBFILES += "${LAYERDIR}/recipes-*/*.bbappend"
BBFILE_COLLECTIONS += "myLayer"
BBFILE_PATTERN_myLayer = "^${LAYERDIR}/"
BBFILE_PRIORITY_myLayer = "10"
LAYERSERIES_COMPAT_myLayer = "kirkstone scarthgap"
LAYERDEPENDS_myLayer = "core"
